<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY6vtfjt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY6vtfjt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerY6vtfjt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerY6vtfjt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerY6vtfjt\appProdProjectContainer(array(
    'container.build_hash' => 'Y6vtfjt',
    'container.build_id' => 'bad5553c',
    'container.build_time' => 1534282962,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY6vtfjt');
